"""add doc_id and source_ref to questions

Revision ID: 6c154dea6975
Revises: 
Create Date: 2026-04-29 18:52:40.245716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c154dea6975'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('doc_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('source_ref', sa.String(length=200), nullable=True))
    op.drop_column('reflection_steps', 'option_label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reflection_steps', sa.Column('option_label', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.drop_column('questions', 'source_ref')
    op.drop_column('questions', 'doc_id')
    # ### end Alembic commands ###
